apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: demo-cloud-deploy-run-pipeline
description: main application pipeline
serialPipeline:
  stages:
  - targetId: run-qsdev
    profiles: [dev]
  - targetId: run-qsprod
    profiles: [prod]
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: run-qsdev
description: Cloud Run development service
run:
  location: projects/onkar-17-cloud/locations/us-central1
executionConfigs:
- defaultPool:
    serviceAccount: cr-cd-sa@onkar-17-cloud.iam.gserviceaccount.com
  usages:
  - RENDER 
  - DEPLOY
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: run-qsprod
description: Cloud Run production service
run:
  location: projects/cysiv-dev-onkarn/locations/us-central1
executionConfigs:
- defaultPool:
    serviceAccount: cr-cd-sa@onkar-17-cloud.iam.gserviceaccount.com
  usages:
  - RENDER 
  - DEPLOY